In [1]:
import os
import copy
import dota2api
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB

%matplotlib inline

In [2]:
API_KEY = '2029A39ECAAB627B5F71CF4C3E30F72D'
api = dota2api.Initialise(API_KEY)

In [3]:
data = pd.read_csv('../data/draft/capmodedata.csv')

In [5]:
data.head(3)

match_id  radiant_win  duration  1is_pick  1team_id  1hero_id  2is_pick  \
0  1928898739         True      2885     False         0        73     False   
1  1928932285         True      1894     False         0        69     False   
2  1928903165         True      2424     False         1        85     False   

   2team_id  2hero_id  3is_pick    ...      17hero_id  18is_pick  18team_id  \
0         1        69     False    ...           41.0      False        0.0   
1         1       102     False    ...           40.0      False        0.0   
2         0        68     False    ...           30.0      False        1.0   

   18hero_id  19is_pick  19team_id  19hero_id  20is_pick  20team_id  20hero_id  
0       81.0       True        1.0      105.0       True        0.0       94.0  
1       28.0       True        1.0       97.0       True        0.0       62.0  
2       47.0       True        0.0       58.0       True        1.0       33.0  

[3 rows x 63 columns]

In [6]:
data.columns

Index(['match_id', 'radiant_win', 'duration', '1is_pick', '1team_id',
       '1hero_id', '2is_pick', '2team_id', '2hero_id', '3is_pick', '3team_id',
       '3hero_id', '4is_pick', '4team_id', '4hero_id', '5is_pick', '5team_id',
       '5hero_id', '6is_pick', '6team_id', '6hero_id', '7is_pick', '7team_id',
       '7hero_id', '8is_pick', '8team_id', '8hero_id', '9is_pick', '9team_id',
       '9hero_id', '10is_pick', '10team_id', '10hero_id', '11is_pick',
       '11team_id', '11hero_id', '12is_pick', '12team_id', '12hero_id',
       '13is_pick', '13team_id', '13hero_id', '14is_pick', '14team_id',
       '14hero_id', '15is_pick', '15team_id', '15hero_id', '16is_pick',
       '16team_id', '16hero_id', '17is_pick', '17team_id', '17hero_id',
       '18is_pick', '18team_id', '18hero_id', '19is_pick', '19team_id',
       '19hero_id', '20is_pick', '20team_id', '20hero_id'],
      dtype='object')

In [14]:
hero_1 = data['1hero_id']
hero_2 = data['2hero_id']
hero_3 = data['3hero_id']
hero_4 = data['4hero_id']
hero_5 = data['5hero_id']
hero_6 = data['6hero_id']
# hero_7 = data['7hero_id']
# hero_8 = data['8hero_id']
# hero_9 = data['9hero_id']

In [9]:
test1 = pd.DataFrame(columns=['1hero_id', '2hero_id', '3hero_id', '4hero_id', '5hero_id'])

In [10]:
test1['1hero_id'] = hero_1
test1['2hero_id'] = hero_2
test1['3hero_id'] = hero_3
test1['4hero_id'] = hero_4
test1['5hero_id'] = hero_5
# test1['6hero_id'] = hero_6
# test1['7hero_id'] = hero_7
# test1['8hero_id'] = hero_8
# test1['9hero_id'] = hero_9

In [12]:
test1.head(3)

1hero_id  2hero_id  3hero_id  4hero_id  5hero_id
0        73        69        71         7        28
1        69       102        32        61        74
2        85        68        75         2        73

In [13]:
X = test1.as_matrix()
X

/home/sulabh/software/anaconda3/envs/dotaenv36/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[ 73,  69,  71,   7,  28],
       [ 69, 102,  32,  61,  74],
       [ 85,  68,  75,   2,  73],
       ...,
       [ 44,  29,  12,  17,  11],
       [  1,  57,  50,  85,  29],
       [ 71, 100,   7,  85,  39]])

In [15]:
y = np.array(hero_6)

In [16]:
y

array([ 68., 112.,  50., ...,  18.,  28.,  11.])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
model = LogisticRegression(n_jobs=4)

In [19]:
model.fit(X_train, y_train)

/home/sulabh/software/anaconda3/envs/dotaenv36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:1232: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 4.
  " = {}.".format(self.n_jobs))


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=4,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
y_pred = model.predict(X_test)
y_pred

array([7., 7., 7., ..., 7., 7., 7.])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
np.unique(y_pred)

In [ ]:
np.unique(y_test)